# Generated by Django 3.1.4 on 2021-02-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210205_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_created',
            new_name='datecreated',
        ),
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='timelimit',
            field=models.CharField(default='timelimit', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
