# Generated by Django 3.1.4 on 2021-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210206_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='description', max_length=10000),
            preserve_default=False,
        ),
    ]
