# Generated by Django 3.1.4 on 2021-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='timelimit',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
